### PR TITLE
Use GitVersion to version the nupkg during build

### PR DESCRIPTION
**Pull request by seankearney**
I've modified the `build.proj` file to leverage GitVersion to calculate the version and use that during nupkg creation.

### CODE REVIEW

**Comment by sayedihashimi** [comment]
@seankearney it looks like the appveyor build failed https://ci.appveyor.com/project/sayedihashimi/package-web/build/1.0.6

**Comment by seankearney** [comment]
I made things a little more simple. This PR is showing basic usage of GitVersion and how it can auto-version the nupkg for us. 

You will notice that this build created a nupkg with version `1.1.9-pullrequest0078` while your manual versioning is already at `1.1.16.3`. GitVersion has some conventions that help it determine what version is calculated. Part of that calculation requires tagging of the repo. The last tag in the repo was `1.1.8.1`. If the repo is tagged with `1.1.16` then the next build would be correctly numbered.

**Comment by sayedihashimi** [comment]
@seankearney that is pretty cool and seems useful as well. I won't have much time to work on it though, I'm really bogged down on a few other projects. You've already helped out a lot on the project so I can make you a contributor and if you'd like to run with it I'm all for that. I'll send over an invite.

**Comment by seankearney** [comment]
@sayedihashimi Thanks. I've tagged the repo at the proper commit with `v1.1.16.3`. With the PR merged, AppVeyor generated a [nupkg v1.1.17](https://ci.appveyor.com/project/sayedihashimi/package-web/build/1.0.10/artifacts).

**Comment by sayedihashimi** [comment]
@seankearney what's your nuget.org username? I will add you as an owner so that you can publish as well. We can also automate publish from appveyor as well if you like. If you want to go that route let me know and I'll add an encrypted nuget api key to the appveyor.yml file.

**Comment by seankearney** [comment]
What are your thoughts on publishing every build to nuget.org? Were you looking to keep prerelease nupkgs on AppVeyor and only final relesases on NuGet?

**Comment by sayedihashimi** [comment]
@seankearney wouldn't every build be overkill? Appveyor already has a project feed which we can publish each build to if we like. From there we can configure VS to use that for CI packages. 

I'm not strongly against it, if you think its a good idea and if we can label the package as `-build` I think its ok.

**Comment by seankearney** [comment]
@sayedihashimi - move this convo back to Issue #77 ?

**Comment by sayedihashimi** [comment]
@seankearney sounds good

**Pull request merged**
